{"subreddit":{"display_name":"Kotlin"},"subreddit_loc":"Котлин","selftext":"Рассмотрим следующий код Swift ([http://online.swiftplayground.run/] (http://online.swiftplayground.run/) ):\n\n    Фонд импорта\n    \n    класс Main {\n    \n        закрытый финал var x: String\n        \n        в этом() {\n            пр ()\n            self.x = \"a\"\n        }\n        \n        func pr () {\n            печать (self.x)\n        }\n    \n    }\n    \n    Главный()\n\n\n\nЭто ведет к:\n\n** main.swift: 10: 9: ошибка: «self» используется в вызове метода «pr» до инициализации всех сохраненных свойств **\n\n** пр () **\n\n\n\nSwift помешал мне использовать * x * до его инициализации. Хорошо.\n\n\n\nТеперь рассмотрим этот Kotlin ([https://play.kotlinlang.org/] (https://play.kotlinlang.org/) ):\n\n\n\n    класс Main {\n    \n        закрытый финал var x: String\n    \n        constructor () {\n            пр ()\n            х = \"бла\"\n        }\n    \n        fun pr () {\n            Println (this.x)\n        }\n    \n    }\n        \n    общественное веселье main () {\n        Главный()\n    }\n\n\n\nРазве мы не должны ожидать, что это тоже не скомпилируется?\n\n\n\nНу, как ни странно, это так. Код компилируется, выводя 'null' во время выполнения.\n\n\n\n*** Почему? *** Это, кажется, значительный недостаток в Котлине.","title":"Почему нулевая безопасность не всегда работает в Котлине?","subreddit_name_prefixed":"r/Kotlin","ups":4,"created":1554533232,"link_flair_background_color":"","id":"b9xrr3","author":{"name":"[deleted]"},"permalink":"/r/Kotlin/comments/b9xrr3/why_doesnt_null_safety_always_work_in_kotlin/","url":"https://www.reddit.com/r/Kotlin/comments/b9xrr3/why_doesnt_null_safety_always_work_in_kotlin/","created_utc":1554504432}