{"subreddit":{"display_name":"Kotlin"},"subreddit_loc":"Котлин","selftext":"Извиняюсь, если этот вопрос супер-очевиден. Я не из Java, поэтому многое для меня чуждо.\n\n\n\nУ меня есть проект, над которым я работаю, который использует модуль \"org.jetbrains.exposed.sql\" для взаимодействия с базой данных sqlite. Все в модуле работает нормально, кроме ... проект умирает, если база данных не найдена. Это должно быть возможным вариантом, поскольку база данных хранится на сетевом диске, а связь может быть плохой. Я рву свои волосы, пытаясь понять, как справиться с этим сценарием в Котлине. Я погуглил каждое видео и учебник на YouTube по обработке исключений, и я на 1000% уверен в том, как обрабатывать исключение в аннотации, но это просто НИКОГДА не работает при запуске команды для подключения к базе данных. (это абсолютно РАБОТАЕТ при попытке других процессов, которые могут потерпеть неудачу, например, часто обучаемое деление на ноль)\n\nНапример:\n\n> попробуй {\nDatabase.connect (\"jdbc: sqlite: $ * databaseName *\", \"org.sqlite.JDBC\")\n}\n>\n> catch (e: SQLException) {\nвернуть ложь\n}\nвернуть истину\n\nЭто \\ _should \\ _ возвращать false, если было исключение, и true, если база данных подключена, однако, если база данных не найдена, программа полностью завершает работу, вместо обработки и возврата false.\n\n>\n>\n> \\ [main \\] WARN Exposed - попытка транзакции № 0 завершилась неудачно: путь к '\\ * \\ * badpath \\ * \\ *': '\\\\\\\\' не существует. Оператор (ы): ноль\n>\n> java.sql.SQLException: путь к '\\ * \\ * badpath \\ * \\ *': '\\\\\\\\' не существует\n>\n> at org.sqlite.SQLiteConnection.open (SQLiteConnection.java:215)\n>\n> ...\n>\n> Процесс завершен с кодом выхода 1\n\nКак вы можете видеть, исключение - это исключение SQLEx (хотя мне больно думать, что вам приходится угадывать все точные типы исключений, которые теоретически может иметь ваш код, чтобы try-catch мог его обработать)\n\n\n\nИтак ... Что я здесь не так делаю? Есть ли более надежный способ сказать Котлину, чтобы он попробовал что-то и просто дал мне знать, если это не удастся, вместо совершения ритуального самоубийства?","title":"Обработка исключений с помощью модулей","subreddit_name_prefixed":"r/Kotlin","ups":6,"created":1572392043,"link_flair_background_color":"","id":"dorhq7","author":{"name":"superwombat"},"permalink":"/r/Kotlin/comments/dorhq7/exception_handling_with_modules/","url":"https://www.reddit.com/r/Kotlin/comments/dorhq7/exception_handling_with_modules/","created_utc":1572363243}